# general modules parameters
dimension: 3
n_runs: 10
random_sample_size: 64
informed_sample_size: 20
plot: False
destination_folder: "./optimization_beta"

# modules
acquisition: "ucb" # "var"
initializer: "sobol"
replicator: "fixed_n" #"max", "sequential"
selector: "variance"
regressor: "Gaussian process regression" # "Gaussian process regression"
convergence_measure: "None"   # use <None> for no convergence measure.

# data simulator parameters
experiment: "auditory_aphasia"
participant: "VPpblz_15_08_14" # ["VPpblz_15_08_14", "VPpboa_15_08_11", "VPpbob_15_08_13", "VPpboc_15_08_17"]
condition: "6D"