# general optimization parameters
dimension: 2
n_runs: 5
random_sample_size: 4
informed_sample_size: 50
plot: False

# data simulator parameters
experiment: "CVEP" # "auditory_aphasia"
participant: "sub-01" #"VPpblz_15_08_14"
condition: "6D"
regression_key: "Gaussian process regression"